### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tyoc213** [butchland/fastai_xla_extensions#2]
- [x] fit one cycle / fit 
- [x] what happens with lr finder?
- [x] unfreeze model makes the gradients explode
- [x] batch transforms are slow :) WHY!
- [x] change default_device to check GPU, then TPU then set CPU.
~- [ ] add patch to  `LMLearner.load_pretrained`and fix method `load_ignore_keys` to work on TPUs~
~- [ ] `textlearner` (`language_model_learner`)  is very slow in running fit_one_cycle (havent finished 1 epoch)~
- [x] test collab learner
- [x] test tabular learner
